### ISSUE TITLE
Draining mode not working correctly

### ISSUE THREAD

**Issue by diazweb** [livekit/egress#106]
We added terminationGracePeriodSeconds to our egress pods. During the recording the pod was in Terminating state  but when I stopped the recorder, this happened: the pod was killed but no video uploaded or webhook sent.

**Comment by frostbyte73** [comment]
Do you have the logs from the instance? If you stopped it using the StopEgress API it should upload before shutting down

**Comment by diazweb** [comment]
Hey @frostbyte73 

Sorry, it was a mistake on our side. We put 360 instead of 3600 in terminationGracePeriodSeconds.

I made another test and everything works fine:

`{"level":"info","ts":1663250687.833193,"logger":"egress","caller":"service/handler.go:129","msg":"egress updated","nodeID":"NE_SzokeCJkGa7g","egressID":"EG_aLuNUf4XMfLh","status":"EGRESS_ACTIVE"}
{"level":"info","ts":1663251034.9843457,"logger":"egress","caller":"server/main.go:101","msg":"exit requested, finishing recording then shutting down","nodeID":"NE_KCK6irWsDAzN","signal":"terminated"}
{"level":"info","ts":1663251034.9844542,"logger":"egress","caller":"service/service.go:97","msg":"shutting down","nodeID":"NE_KCK6irWsDAzN"}
{"level":"info","ts":1663251255.2533677,"logger":"egress","caller":"service/handler.go:129","msg":"egress updated","nodeID":"NE_SzokeCJkGa7g","egressID":"EG_aLuNUf4XMfLh","status":"EGRESS_ENDING"}
{"level":"info","ts":1663251258.4110992,"logger":"egress","caller":"service/handler.go:127","msg":"egress completed","nodeID":"NE_SzokeCJkGa7g","egressID":"EG_aLuNUf4XMfLh"}
{"level":"info","ts":1663251258.4148078,"logger":"egress","caller":"service/service.go:265","msg":"deleting handler temporary directory","nodeID":"NE_KCK6irWsDAzN","path":"/tmp/lkegress/EG_aLuNUf4XMfLh"}`

Closing 👍
