### ISSUE TITLE
Allow full room recording (without composites)

### ISSUE THREAD

**Issue by jezell** [livekit/egress#120]
It appears that currently you can request a composite video, a composite audio track, or an individual track to be saved. For many cases like transcription or offline compositing, it is required to be able to save all the tracks as individual streams without compositing. While this could be done via callbacks, I believe the correct way to do it is probably to extend the egress service with an additional type of egress. These scenarios also typically require some track metadata to be written in order to be able to make use of the individual tracks (https://github.com/livekit/egress/issues/118)

**Comment by frostbyte73** [comment]
Added to livekit CreateRoomRequest in #1011
