### ISSUE TITLE
Problem running docker "open config.yaml: no such file or directory"

### ISSUE THREAD

**Issue by eyeengine** [livekit/egress#126]
When using the command:

docker run --rm \
     -e EGRESS_CONFIG_FILE=/out/config.yaml \
     -v ~/livekit-egress:/out \
     livekit/egress

I get the error:
"+ mkdir -p /tmp/lkegress
+ exec egress
open /config.yaml: no such file or directory"

For that reason I can't use or test egress

**Comment by biglittlebigben** [comment]
I could not reproduce the issue above:
```
docker run --rm \
-e EGRESS_CONFIG_FILE=/out/config.yaml \         
-v ~/go/src/github.com/livekit/egress/test:/out \
livekit/egress
+ export TMPDIR=/tmp/lkegress
+ TMPDIR=/tmp/lkegress
+ pulseaudio -D --verbose --exit-idle-time=-1 --system --disallow-exit
W: [pulseaudio] main.c: Running in system mode, but --disallow-module-loading not set.
N: [pulseaudio] main.c: Running in system mode, forcibly disabling SHM mode.
I: [pulseaudio] main.c: Daemon startup successful.
+ '[' -z /tmp/lkegress ']'
+ mkdir -p /tmp/lkegress
+ exec egress
{"level":"info","ts":1665016206.7505462,"logger":"egress","caller":"redis/redis.go:53","msg":"connecting to redis","nodeID":"NE_mYWBmTNqsiC7","sentinel":false,"addr":"192.168.65.2:6379"}
{"level":"debug","ts":1665016206.7529986,"logger":"egress","caller":"service/service.go:68","msg":"starting service","nodeID":"NE_mYWBmTNqsiC7"}
{"level":"debug","ts":1665016206.7538588,"logger":"egress","caller":"service/service.go:93","msg":"service ready","nodeID":"NE_mYWBmTNqsiC7"}
^C{"level":"info","ts":1665016208.4425173,"logger":"egress","caller":"server/main.go:103","msg":"exit requested, stopping recording and shutting down","nodeID":"NE_mYWBmTNqsiC7","signal":"interrupt"}
{"level":"info","ts":1665016208.4427583,"logger":"egress","caller":"service/service.go:98","msg":"shutting down","nodeID":"NE_mYWBmTNqsiC7"}
```

`open open /config.yaml` is unexpected here. What version of the server are you using?

**Comment by eyeengine** [comment]
I am using ubuntu 18, it is blank, it has nothing.

**Comment by eyeengine** [comment]
I am using the command:
"docker run --rm -e EGRESS_CONFIG_BODY="$(cat config.yaml)" -v /root/record:/out livekit/egress"

However I get the following error:
+ export TMPDIR=/tmp/lkegress
+ TMPDIR=/tmp/lkegress
+ pulseaudio -D --verbose --exit-idle-time=-1 --system --disallow-exit
W: [pulsaudio] main.c: Running in system mode, but --disallow-module-loading not set.
N: [pulsaudio] main.c: Running in system mode, forcibly disabling SHM mode.
I: [pulsaudio] main.c: Daemon startup successful.
+ '[' -z /tmp/lkegress ']'
+ mkdir -p /tmp/lkegress
+ exec egress
{"level":"info","ts":1665045471.3235445,"logger":"egress","caller":"redis/redis.go:53","msg":"connecting to redis","nodeID" :"NE_bjdCZqenEuLW","sentinel":false,"addr":"localhost:6379"}
unable to connect to redis: dial tcp 127.0.0.1:6379: connect: connection refused


It does not connect to redis-server, I have tested redis with:
redis-cli -h localhost -p 6379 ping

The result is:
 PONG

So redis is working perfectly.

**Comment by biglittlebigben** [comment]
This is because the redis server runs on the host and not the container, so is not accessible over localhost for the egress server.

https://github.com/livekit/egress/blob/main/README.md has further documentation on how to configure redis and egress when running locally. Note that 172.17.0.1 should be used on linux instead of 192.168.65.2.

**Comment by Spearking** [comment]
Configure Redis to work with ip address **0.0.0.0** and restart the service.

Then connect the Egress with **172.17.0.1 (local)** or use the IP if you have Redis **on the same network** share.

I hope it helps you :)
