### ISSUE TITLE
StartedAt on egressInfo appears not to be accurate

### ISSUE THREAD

**Issue by neilkinnish** [livekit/egress#135]
Firstly, Great project!

I'm planning to run some tests on this, but can I just sense check.

I am seeing incorrect StartedAt on egressInfo data via Webhook events. 

I may be missing something – a quick look at the repo and it appears that the StartedAt is generated before the recording has started?

https://github.com/livekit/egress/blob/51fcd62880eac14298845b6a76bcc3df380f6021/pkg/pipeline/pipeline.go#L159

Thanks

**Comment by frostbyte73** [comment]
That is when the service was started, used to track/debug reservations and autoscaling.
There is a separate StartedAt inside the returned FileInfo/StreamInfo which shows when the actual recording has started:
https://github.com/livekit/egress/blob/main/pkg/pipeline/pipeline.go#L318
https://github.com/livekit/egress/blob/main/pkg/pipeline/pipeline.go#L493

**Comment by frostbyte73** [comment]
Made a mistake with above comment - the FileInfo/StreamInfo only returns duration, not StartedAt

**Comment by neilkinnish** [comment]
Ah yes of course, makes sense `Info`.

> Will update FileInfo to include StartedAt/EndedAt as well

Perfect! thanks.

**Comment by frostbyte73** [comment]
Added in #136
