### ISSUE TITLE
Can we update gstreamer to 1.20.4?

### ISSUE THREAD

**Issue by shentianyu93** [livekit/egress#138]
GStreamer 1.20.4 stable bug fix release:
matroska-mux: also allow width + height changes for avc3|hev1|vp8|vp9

{"level":"error","ts":1665983528.9609885,"logger":"egress","caller":"pipeline/pipeline.go:734","msg":"pipeline error","nodeID":"NE_Ly4GjPApXo78","egressID":"EG_tSXrjvsSuF55","debug":"../gst/matroska/matroska-mux.c(1111): gst_matroska_mux_video_pad_setcaps (): /GstPipeline:pipeline/GstBin:input/GstWebMMux:webmmux0:\nCaps changes are not supported by Matroska\nCurrent: `video/x-vp8, framerate=(fraction)0/1, height=(int)540, width=(int)960, profile=(string)0`\nNew: `video/x-vp8, framerate=(fraction)0/1, height=(int)720, width=(int)1280, profile=(string)0`","message":"Could not multiplex stream.","error":"Could not multiplex stream.","stacktrace":"github.com/livekit/egress/pkg/pipeline.(*Pipeline).handleError\n\t/workspace/pkg/pipeline/pipeline.go:734\ngithub.com/livekit/egress/pkg/pipeline.(*Pipeline).messageWatch\n\t/workspace/pkg/pipeline/pipeline.go:289\ngithub.com/tinyzimmer/go-gst/gst.goBusFunc\n\t/root/go/pkg/mod/github.com/livekit/go-gst@v0.0.0-20220603230042-cef031256427/gst/cgo_exports.go:128\n_cgoexp_752bbda710ba_goBusFunc\n\t_cgo_gotypes.go:17363\nruntime.cgocallbackg1\n\t/usr/lib/go-1.18/src/runtime/cgocall.go:314\nruntime.cgocallbackg\n\t/usr/lib/go-1.18/src/runtime/cgocall.go:233\nruntime.cgocallback\n\t/usr/lib/go-1.18/src/runtime/asm_amd64.s:971\nruntime.systemstack_switch\n\t/usr/lib/go-1.18/src/runtime/asm_amd64.s:436\nruntime.cgocall\n\t/usr/lib/go-1.18/src/runtime/cgocall.go:167\ngithub.com/tinyzimmer/go-glib/glib._Cfunc_g_main_loop_run\n\t_cgo_gotypes.go:2822\ngithub.com/tinyzimmer/go-glib/glib.(*MainLoop).Run.func1\n\t/root/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.25/glib/gmainloop.go:53\ngithub.com/tinyzimmer/go-glib/glib.(*MainLoop).Run\n\t/root/go/pkg/mod/github.com/tinyzimmer/go-glib@v0.0.25/glib/gmainloop.go:53\ngithub.com/livekit/egress/pkg/pipeline.(*Pipeline).Run\n\t/workspace/pkg/pipeline/pipeline.go:218\ngithub.com/livekit/egress/pkg/service.(*Handler).HandleRequest.func2\n\t/workspace/pkg/service/handler.go:58"}

Will this release fix this problem?

**Comment by frostbyte73** [comment]
@shentianyu93 I'll be updating and testing this today

**Comment by frostbyte73** [comment]
updated in #140

**Comment by shentianyu93** [comment]
> @shentianyu93 I'll be updating and testing this today

@frostbyte73 Thank you very much.

when we use egress, found another problem.
Start recording with TrackComposite，and use StopEgress to stop recording,it frequently runs timeout，report 'pipeline frozen'
`go func() {
			p.Logger.Debugw("sending EOS to pipeline")
			p.eosTimer = time.AfterFunc(eosTimeout, func() {
				p.Logger.Errorw("pipeline frozen", nil)
				p.Info.Error = "pipeline frozen"
				p.stop()
			})

			switch s := p.in.(type) {
			case *sdk.SDKInput:
				s.SendEOS()
			case *web.WebInput:
				p.pipeline.SendEvent(gst.NewEOSEvent())
			}
		}()`

Is this a problem with gstreamer?
