### ISSUE TITLE
The number of channels of websocket streaming is not enforced.

### ISSUE THREAD

**Issue by samhumeau** [livekit/egress#147]
Currently nothing seems to enforce that the PCMs that the websocket egress outputs have 2 channels (aka is stereo).
This information is needed for the PCM to be used reliably (for e.g. speech to text), otherwise the PCM might be badly interpreted (typically if using mono, it will be interpreted with a 2x speed).

As discussed offline with @frostbyte73 and @davidzhao, the simplest solution would be to enforce it during the conversion from original encoding to raw PCM.

**Comment by frostbyte73** [comment]
added in #146
