### ISSUE TITLE
Track egress to file unnecessarily transcoding

### ISSUE THREAD

**Issue by joaocpo** [livekit/egress#198]
**Describe the bug**
I'm experiencing an unexpectedly high load average while using egress. I'm using _livekit-cli load-test_ to send H264 streams to a room and using _livekit-cli start-track-egress_ to record those tracks. I expected the tracks to be recorded with no transcoding as stated in the [documentation](https://docs.livekit.io/server/egress/#track-egress), but apparently some transcoding is happening.

**Server**
- egress version 1.5.0
- Egress binary directly on Debian 11 running on an EC2’s c5.2xlarge (8vCPUs, 16GB RAM)

**Client**
- livekit-cli

**To Reproduce**
1.   start a room with a pub and a sub:
```
livekit-cli load-test --api-key $LKKEY --api-secret $LKSECRET --url $LKURL --room $ROOM_NAME --publishers 1 --subscribers 1
```
2.   get the participant and get the video track
```
livekit-cli list-participants --api-key $LKKEY --api-secret $LKSECRET --url $LKURL --room $ROOM_NAME
livekit-cli get-participant --identity $PARTICIPANT_ID --api-key $LKKEY --api-secret $LKSECRET --url $LKURL --room $ROOM_NAME
```
3.  start recording the track
```
livekit-cli start-track-egress --api-key $LKKEY --api-secret $LKSECRET --url $LKURL --request $REQFILE
```
4.   REQFILE has the following format:
```
{ 
  "room_name": "$ROOM_NAME",
  "track_id": "$TRACK",
  "file": {
    "filepath": "$ROOM_NAME.mp4",
    "s3": {
      "access_key": "KEY",
      "secret": "SECRET",
      "region": "us-east-1",
      "bucket": "BUCKET" 
    }
  } 
 } 
```
5.  After this I sleep for 300s
6. repeat steps 1-5 four times in order to trigger 4 active egresses.
7. Observe load average values (using htop for instance) during the process. I saw values over 12.

**Expected behavior**
For 4 active egress I expected to see a very low load average value, maybe around 1.

**Additional context**
This issue was [discussed](https://livekit-users.slack.com/archives/C01KVTJH6BX/p1671026919649979) with Benjamin Pracht, and he suggested that the H264 track from the cli  is getting transcoded on the egress causing the high load values I was experiencing.

**Comment by davidzhao** [comment]
Thank you for the report. This was fixed in #200. It will be included in the next release.
