### ISSUE TITLE
Store in local disk

### ISSUE THREAD

**Issue by jibon57** [livekit/egress#23]
Thanks for the new recording system. Not all the users are using online storage services. How to store files in local disk?

**Comment by dwirya** [comment]
Hi @jibon57 , you can use `EncodedFileOutput` or `DirectFileOutput` as seen in the protobuf: https://github.com/livekit/protocol/blob/main/livekit_egress.proto

**Comment by davidzhao** [comment]
Unfortunately local files are not compatible with the design of egress. The idea for egress is to be a stateless "worker" instance. they should not keep any state and can be scaled down at any time.

Keeping files locally on disk would violate that design goal.

**Comment by jibon57** [comment]
@davidzhao thanks. But user may want to use NFS or other network storage disk attached with server too

**Comment by davidzhao** [comment]
yeah you are right those use cases probably exist somewhere.

Though it gets really complicated to configure / understand. Is this a use case that you actually have? or just thinking that someone might have this need?

**Comment by jibon57** [comment]
Yes, I'm using NFS for myself. In https://github.com/mynaparrot/plugNmeet-recorder user can point NFS mount point & after process data copied to that disk. In docker I think you can easily mount any local path & copy the final data.

**Comment by jibon57** [comment]
First of all user will require to mount any network disk with the server. Later re-mount in docker. Even if user have powerful server with bigger disk capacity may want to store recordings into that particular server too. So having this feature will be helpful.

**Comment by davidzhao** [comment]
makes sense.. it definitely can be used that way. I'll keep the ticket open. You are welcome to take a stab on it if you'd like. (or anyone else who might need it).

**Comment by frostbyte73** [comment]
@jibon57 if you run the docker container with a mounted directory, you can write to local storage. 
Our integration tests do this by running `docker run --rm -v ~/livekit/egress/test:/out egress-test` and using `/out/output/filename.mp4` as the `Filepath` with requests

**Comment by davidzhao** [comment]
@jibon57 does this resolve your needs? @frostbyte73 do you think we should update docs to reflect this use case?

**Comment by jibon57** [comment]
@davidzhao thanks. Yes, this will work. Having documentation will be helpful. Also if we can copy the final output to seperate directory will be good too.
