### ISSUE TITLE
Stream to RTMP server 

### ISSUE THREAD

**Issue by anhtu-phan** [livekit/egress#266]
Hello team, 

I am trying to stream a video by [StartTrackCompositeEgress](https://docs.livekit.io/server/egress/#starttrackcompositeegress) via HTTP post from the flutter client as bellow

`var headers = {
            'Content-Type': 'application/json',
            'Authorization': 'Bearer $token'
          };
          var data = {
            "roomName": roomName,
            "video_track_id": t.sid,
            "stream": {
              "urls": ["rtmp://host/app/$roomName"]
            }
          };
          http.Response res = await http.post(
            Uri.parse(
                "[livekit_endpoint]/twirp/livekit.Egress/StartTrackCompositeEgress"),
            headers: headers,
            body: jsonEncode(data),
          );`

and I saw the log on egress service as below 
`WARN	egress	service/handler_deprecated.go:144	egress failed	{"nodeID": "NE_C22VGH2qB8Y6", "handlerID": "EGH_gz5Ep48aYbbM", "egressID": "EG_bfLAV9ozRAqo", "egressID": "EG_bfLAV9ozRAqo", "request_type": "track_composite", "output_type": "stream", "error": "could not connect after timeout"}
`

Could you help me to solve this issue or give me an example of how to stream track (video) published from the flutter app to the RTMP server?

Thank you so much.

**Comment by davidzhao** [comment]
Please provide more details as how your servers have been set up. This error means the Egress instance isn't able to connect to livekit server.

See [deployment docs](https://docs.livekit.io/oss/deployment/egress/#config) regarding how Egress should be configured.

**Comment by anhtu-phan** [comment]
@davidzhao

I run Egress with command 

`docker run --rm -e EGRESS_CONFIG_FILE=/out/config.yaml -v ~/livekit-egress:/out livekit/egress`

and the below is config.yaml 

`log_level: debug`
`api_key: APIjJAk6JcZQgzc`
`api_secret: 04Oap9Nja0DhMCFPQ4Wbc4PH7mFZh5723TFoOlrKIIK`
`ws_url: ws://172.17.0.1:7880`
`insecure: true`
`redis:`
`  address: 172.17.0.1:6379`

I run live-kit server like in setup for dev `livekit-server --dev --config config.yaml`
The bellow is config.yaml file

`port: 7880`
`redis:`
`  address: 172.17.0.1:6379`
`rtc:`
`  port_range_start: 50000`
`  port_range_end: 60000`
`  tcp_port: 7881`
`  use_external_ip: true`
`keys:`
`  APIjJAk6JcZQgzc: 04Oap9Nja0DhMCFPQ4Wbc4PH7mFZh5723TFoOlrKIIK`

Thank you so much for your help!

**Comment by davidzhao** [comment]
Can you try `use_external_ip: false` when configuring livekit? I think Egress isn't able to connect to livekit due to some port/configurations. If that doesn't work, can you attach the logs from livekit-server while you are trying the egress request.

**Comment by anhtu-phan** [comment]
hello, thank you for the suggestion.

I change `ws_url: ws://172.17.0.1:7880` to `ws_url: http://172.17.0.1:7880` and it works for me.

Thank you so much for your time and support
