### ISSUE TITLE
Buffer too small

### ISSUE THREAD

**Issue by frostbyte73** [livekit/egress#27]
For some tracks, the egress recording stops almost immediately after it starts with the error: ```{"logger":"egress","caller":"source/appwriter.go:181","msg":"could not read packet","egressID":"EG_JWbiQTnRuBaa","trackID":"TR_VS2deqoQWnD23f","kind":"video","error":"buffer too small","stacktrace":"[github.com/livekit/egress/pkg/pipeline/source.(*appWriter).start](http://github.com/livekit/egress/pkg/pipeline/source.(*appWriter).start)\n\t/workspace/pkg/pipeline/source/appwriter.go:181"}```

**Comment by little51** [comment]
I use livekit/egress:v1.0.3 docker images,It's worked!
