### ISSUE TITLE
[FEATURE] Support AWS S3 presigned url

### ISSUE THREAD

**Issue by imredobos** [livekit/egress#330]
**Is your feature request related to a problem? Please describe.**
Add support for AWS S3 presigned url to save the egress' output.

**Describe the solution you'd like**
A simple S3 presigned url should be enough to upload to S3.

**Describe alternatives you've considered**
-

**Additional context**
-

**Comment by davidzhao** [comment]
this wouldn't fit the current API very well. For certain output types (segmented output, etc), we'll need to write to multiple destinations.

the API is already fairly complex so we'll be closing this issue for now in order to avoid increasing that complexity.
