### ISSUE TITLE
[FEATURE] Auto stop recording

### ISSUE THREAD

**Issue by calvin-seo** [livekit/egress#358]
**Is your feature request related to a problem? Please describe.**
I only want to record first five minutes of each track. To achieve this under current circumstance, an extra application should watch time goes and manually stop egress after each recording starts.

**Describe the solution you'd like**
Maybe an extra parameter, which specifies the maximum time limit for recording, in each egress recording apis. Then egress will stop by either the max time or a manual stop request

**Comment by frostbyte73** [comment]
You can use [session limits](https://github.com/livekit/egress/blob/main/pkg/config/base.go#L91) and they will be automatically stopped after that amount of time

**Comment by calvin-seo** [comment]
@frostbyte73 
as far as I understand the config you mention applies to all recording reqeust, but what i want is controlling the limit for each recording reqeust via livekit API server.

**Comment by davidzhao** [comment]
I think given your requirements, it's best to control that business logic on your end. We provide APIs to stop the Egress at any point.

At this point, we'd like to focus on making Egress reliable and performant, instead of adding too many different features to it.
