### ISSUE TITLE
[BUG] Track egress ended_at event emitted after room_finished event

### ISSUE THREAD

**Issue by imredobos** [livekit/egress#364]
**Describe the bug**
When a track egress is active for a participant's track and the participant leaves the room, the corresponding recording participant still lives in the room and is only removed when the room ends. It causes that 3 events: participant_left, room_finished, and egress_ended are basically emitted at the same time, and the track record lasts until the end of the meeting.
The expected behavior would be that when the participant leaves the room, the recording participant also leaves the room, and the egress_ended event is emitted immediately.

**Egress Version**
1.7.1

**Egress Request**
-

**Additional context**
Livekit version: 1.4.2

**Logs**
-

**Comment by frostbyte73** [comment]
The `egress_ended` event contains the final status, which needs to wait for the pipeline to close and for files to upload. 
We do not make any guarantees about the ordering of webhook events between egress and rooms
