### ISSUE TITLE
[BUG] Egress does not recording anything after Redis channel is full

### ISSUE THREAD

**Issue by calvin-seo** [livekit/egress#365]
**Describe the bug**
An error below is repeatedly printed out, and the egress stop processing any more recording,
```
redis: 2023/05/18 05:26:39 pubsub.go:666: redis: &{%!s(*redis.PubSub=&{0x40001be600 0x80f1e0 0x89ce30 {0 0} 0x4000146be0 map[EG_START:{}] map[] map[] false 0x400010e660 0x400084aae0 {1 {0 0}} 0x40004e48c0 <nil>}) %!s(chan *redis.Message=0x4000509920) %!s(chan interface {}=<nil>) %!s(chan struct {}=0x400010e7e0) %!s(int=100) %!s(time.Duration=60000000000) %!s(time.Duration=3000000000)} channel is full for 1m0s (message is dropped)
```

**Egress Version**
1.6.2, running on EKS

**Additional context**
While the error is getting printed out, the prometheus metric shows that there is one room composite going on the pod

**Logs**
![image](https://github.com/livekit/egress/assets/99635573/fa1f0c97-18a9-47cc-84a6-e7adb50d2e85)

**Comment by frostbyte73** [comment]
update livekit-server or add `egress: use_psrpc: true` to the livekit-server config. You are using the deprecated communication layer
