### ISSUE TITLE
[BUG] Backward PTS

### ISSUE THREAD

**Issue by refaldyrk** [livekit/egress#383]
**Describe the bug**
<img width="952" alt="image" src="https://github.com/livekit/egress/assets/88225369/a65a7c39-55dd-41ac-a5f5-58231f0e60b5">

I Found 2023-06-08T02:25:04.929Z        WARN    egress  sdk/appwriter.go:354    backwards pts   {"nodeID": "NE_HLyg5CAPKToP", "handlerID": "EGH_gxrciRYnwLNz", "clusterID": "", "egressID": "EG_Aha6VVsxPwVn", "trackID": "TR_VCbzYrt2RBr4VB", "kind": "video", "pts": "8h38m25.712864408s", "lastPTS": "8h38m25.714581136s"}

**Egress Version**
https://github.com/livekit/egress/commit/0870ed6cff7ec117c72446593de18bad29725fd5

**Egress Request**

**Additional context**

**Logs**
<img width="952" alt="image" src="https://github.com/livekit/egress/assets/88225369/a65a7c39-55dd-41ac-a5f5-58231f0e60b5">

I Found 2023-06-08T02:25:04.929Z        WARN    egress  sdk/appwriter.go:354    backwards pts   {"nodeID": "NE_HLyg5CAPKToP", "handlerID": "EGH_gxrciRYnwLNz", "clusterID": "", "egressID": "EG_Aha6VVsxPwVn", "trackID": "TR_VCbzYrt2RBr4VB", "kind": "video", "pts": "8h38m25.712864408s", "lastPTS": "8h38m25.714581136s"}

**Comment by davidzhao** [comment]
Please provide detailed repro steps. What steps did you use to get to this point? Did you build the latest yourself?

**Comment by davidzhao** [comment]
Additionally, please repost any logs by including text blocks or upload them as text attachments. Screenshot logs are not legible.

**Comment by refaldyrk** [comment]
yes, i build latest myself

**Comment by refaldyrk** [comment]
> Selain itu, silakan posting ulang log apa pun dengan memasukkan blok teks atau mengunggahnya sebagai lampiran teks. Log tangkapan layar tidak terbaca.

2023-06-08T02:25:04.929Z WARN egress sdk/appwriter.go:354 backwards pts {"nodeID": "NE_HLyg5CAPKToP", "handlerID": "EGH_gxrciRYnwLNz", "clusterID": "", "egressID": "EG_Aha6VVsxPwVn", "trackID": "TR_VCbzYrt2RBr4VB", "kind": "video", "pts": "8h38m25.712864408s", "lastPTS": "8h38m25.714581136s"}

and 

023-06-08T06:30:06.659Z        WARN    egress  service/handler.go:195  egress failed   {"nodeID": "NE_i2s7kefRtDFq", "handlerID": "EGH_nTXjRB2wEBYc", "clusterID": "", "egressID": "EG_NmVcVUtvah4i", "egressID": "EG_NmVcVUtvah4i", "request_type": "track_composite", "output_type": "file", "error": "pipeline frozen"}

**Comment by frostbyte73** [comment]
Fixed in v1.7.4

**Comment by refaldyrk** [comment]
thank u sir
