### ISSUE TITLE
Redis + Egress = memory is leaking... [BUG]

### ISSUE THREAD

**Issue by cpp-pilot** [livekit/egress#429]
**Describe the bug**
The egress objects continues to hang even after the room is deleted and the egress is stopped.

After the conversation is completed and the last participant leaves, the egress should take this into account and not leave remnants in the form of objects that accumulate in Redis.

**Egress Version**
1.7.5

**Comment by davidzhao** [comment]
this is not a leak. by design the Egress object gets cleaned up after 24h. The reason for this is so when you listEgress after the session is over, it would still be returned.

cleanup takes place [here](https://github.com/livekit/livekit/blob/master/pkg/service/redisstore.go#L438)
