### ISSUE TITLE
HLS code is referencing unreleased version of livekit module??

### ISSUE THREAD

**Issue by mwk24** [livekit/egress#44]
https://github.com/livekit/egress/blob/712a0112c42f43d974b66a5e8e4e5378b506ba69/test/track_composite_test.go#L179

TrackCompositeEgressRequest_Segments doesn't seem to exist when I'm testing

**Comment by davidzhao** [comment]
HLS output will be in the next version of Egress :) See [protocol](https://github.com/livekit/protocol/blob/main/livekit_egress.proto#L37)
