### ISSUE TITLE
Support for VP9-encoded tracks

### ISSUE THREAD

**Issue by onthegit** [livekit/egress#453]
Is VP9 planned ?

**Comment by davidzhao** [comment]
Can you be more specific to what you mean?

**Comment by onthegit** [comment]
Currently only VP8 codec is supported. Videos with VP9 codec can not be exported with livekit egress.

**Comment by davidzhao** [comment]
I understand! Yeah, we'll be supporting VP9 and AV1 exports soon.

**Comment by onthegit** [comment]
@davidzhao  Thanks. Should I leave this open to track progress or close it?

**Comment by davidzhao** [comment]
Let's leave it open to track. We'll close it when support has been added :)

**Comment by onthegit** [comment]
Nice adding support for vp9. 

For vp9 svc encoding there is an example here:
https://github.com/webmproject/libvpx/blob/main/examples/vp9_spatial_svc_encoder.c

**Comment by onthegit** [comment]
Thank you for this,
