### ISSUE TITLE
[BUG] {publisher_identity} not working

### ISSUE THREAD

**Issue by kylee001** [livekit/egress#466]
**Describe the bug**
request file name template {publisher_identity} not working

**Egress Version**
LiveKit cloud

**Egress Request**
<img width="548" alt="image" src="https://github.com/livekit/egress/assets/124127312/cb2e9440-4734-4c7b-93c9-ee0366ca4100">

**Additional context**
<img width="668" alt="image" src="https://github.com/livekit/egress/assets/124127312/2ec92f90-49cf-4907-b463-cdb7d49b6478">

**Logs**
also *.json I can't find publisher_identity
<img width="1807" alt="image" src="https://github.com/livekit/egress/assets/124127312/8fb2eddc-23e3-4762-8428-78446eee571b">

**Comment by frostbyte73** [comment]
Fixed in #497
