### ISSUE TITLE
Is there any plan to support on-demand asynchronous transcription?

### ISSUE THREAD

**Issue by lcodecorex** [livekit/egress#479]
**Is your feature request related to a problem? Please describe.**
You know, real-time transcription is very expensive. Therefore, we only provide playback access after the session ends, and users can transcribe and play back as needed. Another scenario is to perform transcription operations during the low peak period at night to reduce server costs.

**Describe the solution you'd like**
Can we only store media data and information during the conversation and then transcribe it at the appropriate time?

**Comment by frostbyte73** [comment]
If I understand your question correctly, you can record using audio-only egress, and then perform transcription on the fly or at night as you said. We do not plan to support transcription within egress.
