### ISSUE TITLE
[FEATURE] Independent egress recording without any redis.

### ISSUE THREAD

**Issue by heyarviind** [livekit/egress#500]
**Is your feature request related to a problem? Please describe.**
We have more than 15 ec2 instances running of livekit, which do not share any redis. Is there a way to record each server's session without bringing the redis in between?
 
**Describe the solution you'd like**
For now, we want to use web recording, we will send the URL to Egress, and it will open it and start recording. It doesn't have to connect to redis to do the same thing. This will solve our issue of recording multiple sessions from different servers.

**Describe alternatives you've considered**
For an alternative solution, we are thinking of building our own solution which will receive a URL open it in chrome, and start recording. After it finishes recording, it will upload it to s3, just like egress.

**Additional context**

**Comment by frostbyte73** [comment]
Redis, or another [message bus](https://github.com/livekit/psrpc/blob/main/bus.go) implementation, is required for load balancing the egress requests. Grpc (or any other standard http load balancing) cannot be used, these load balancers assume requests will be short lived, and strategies such as the typical round robin do not work when requests can last hours and each instance can only handle a couple requests at a time.  

To achieve this, you would need to create and deploy a separate service with an http endpoint (which acts as the Egress service in LiveKit server), and still put all egress instances on the same redis or nats cluster, or build a new message bus, or implement your own load balancing some other way
