### ISSUE TITLE
[BUG]E: [pulseaudio] main.c: Daemon startup failed.

### ISSUE THREAD

**Issue by shoyu666** [livekit/egress#501]
**Describe the bug**
egress docker container crash

**Egress Version**
v1.7

**Egress Request**
Post the request here (be sure to remove any PII).

**Additional context**
cpu: arm64

i have try

enable_chrome_sandbox:true
seccomp=chrome-sandboxing-seccomp-profile.json or seccomp=unconfined

**Logs**
egress  | 2023-09-22T15:34:10.062+0800  INFO    egress  service/service.go:132  request validated       {"nodeID": "NE_Lg2vv79M2g7H", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "requestType": "web", "outputType": "stream", "room": "", "request": {"Web":{"url":"http://192.168.0.29:30064/#/liveKitRoom?liveUrl=wss://xxxx.com&token=xxxx","Output":{"Stream":{"urls":["rtmp://192.168.0.29:30010/live/{169...c_1}"]}},"Options":null,"stream_outputs":[{"urls":["rtmp://192.168.0.29:30010/live/{169...c_1}"]}]}}}
egress  | 2023-09-22T15:34:10.105+0800  INFO    egress  redis/redis.go:127      connecting to redis     {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "simple": true, "addr": "172.18.0.12:6379"}
egress  | 2023-09-22T15:34:10.856+0800  INFO    egress  pipeline/watch.go:232   pipeline playing        {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ"}
egress  | 2023-09-22T15:34:10.857+0800  INFO    egress  service/handler.go:226  egress updated  {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "egressID": "EG_TvQfiR5NZFkQ", "requestType": "web", "outputType": "stream", "status": "EGRESS_ACTIVE"}
egress  | 2023-09-22T15:34:12.992+0800  DEBUG   egress  [gst warning] parse_ecma_array: Expected array with 1 elements, but read 10     {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "caller": "../gst/rtmp2/rtmp/amf.c:802"}
egress  | 2023-09-22T15:34:12.994+0800  DEBUG   egress  [gst warning] gst_rtmp_connection_handle_cm: Server sent response "_result" without transaction{"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "caller": "../gst/rtmp2/rtmp/rtmpconnection.c:1074"}
egress  | 2023-09-22T15:34:12.994+0800  DEBUG   egress  [gst warning] gst_rtmp_connection_handle_cm: Server sent response "_result" without transaction{"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "caller": "../gst/rtmp2/rtmp/rtmpconnection.c:1074"}
egress  | 2023-09-22T15:35:06.559+0800  INFO    egress  service/handler.go:226  egress updated  {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "egressID": "EG_TvQfiR5NZFkQ", "requestType": "web", "outputType": "stream", "status": "EGRESS_ENDING"}
egress  | 2023-09-22T15:35:06.928+0800  DEBUG   egress  [gst warning] gst_flv_mux_buffer_to_tag_internal: Got backwards dts! (0:00:54.366000000 < 0:00:54.474000000)    {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "caller": "../gst/flv/gstflvmux.c:1241", "object": "sink_1"}
egress  | 2023-09-22T15:35:06.935+0800  INFO    egress  pipeline/watch.go:125   EOS received    {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ"}
egress  | 2023-09-22T15:35:06.938+0800  DEBUG   egress  [gst warning] audioringbuffer_thread_func: error reading data -1 (reason: Resource temporarily unavailable), skipping segment   {"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "caller": "../gst-libs/gst/audio/gstaudiosrc.c:227", "object": "pulsesrc0"}
egress  | 2023-09-22T15:35:06.939+0800  DEBUG   egress  [gst warning] gst_rtmp_connection_handle_cm: Server sent response "_result" without transaction{"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "caller": "../gst/rtmp2/rtmp/rtmpconnection.c:1074"}
egress  | 2023-09-22T15:35:06.942+0800  DEBUG   egress  [gst warning] gst_rtmp_connection_handle_cm: Server sent response "_result" without transaction{"nodeID": "NE_Lg2vv79M2g7H", "handlerID": "EGH_Pb2cyGiBmMyu", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "caller": "../gst/rtmp2/rtmp/rtmpconnection.c:1074"}
egress  | X connection to :2062141659 broken (explicit kill or server shutdown).
egress  | 2023-09-22T15:35:07.044+0800  WARN    egress  service/handler.go:214  egress failed   {"nodeID": "NE_Lg2vv79M2g7H", "clusterID": "", "egressID": "EG_TvQfiR5NZFkQ", "requestType": "web", "outputType": "stream", "error": "internal error"}
egress  | 2023-09-22T15:35:07.049+0800  INFO    egress  service/service.go:102  shutting down   {"nodeID": "NE_Lg2vv79M2g7H", "clusterID": ""}
egress  | 2023-09-22T15:35:07.049+0800  INFO    egress  service/service.go:218  closing server  {"nodeID": "NE_Lg2vv79M2g7H", "clusterID": ""}
egress  | + rm -rf '/home/egress/tmp/*'
egress  | + rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse
egress  | + pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
egress  | E: [pulseaudio] main.c: Daemon startup failed.
egress  | + rm -rf '/home/egress/tmp/*'
egress  | + rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse
egress  | + pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
egress  | E: [pulseaudio] main.c: Daemon startup failed.
egress  | + rm -rf '/home/egress/tmp/*'
egress  | + rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse
egress  | + pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
egress  | E: [pulseaudio] main.c: Daemon startup failed.
egress  | + rm -rf '/home/egress/tmp/*'
egress  | + rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse
egress  | + pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
egress  | E: [pulseaudio] main.c: Daemon startup failed.
egress  | + rm -rf '/home/egress/tmp/*'
egress  | + rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse
egress  | + pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
egress  | E: [pulseaudio] main.c: Daemon startup failed.
egress  | + rm -rf '/home/egress/tmp/*'
egress  | + rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse
egress  | + pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
egress  | E: [pulseaudio] main.c: Daemon startup failed.
egress  | + rm -rf '/home/egress/tmp/*'
egress  | + rm -rf /var/run/pulse /var/lib/pulse /home/egress/.config/pulse
egress  | + pulseaudio -D --verbose --exit-idle-time=-1 --disallow-exit
egress  | E: [pulseaudio] main.c: Daemon startup failed.
<img width="1206" alt="image" src="https://github.com/livekit/egress/assets/20290812/d3e6eaf8-deea-43a8-b00e-67465782ee16">

**Comment by heyarviind** [comment]
Getting same issue

**Comment by frostbyte73** [comment]
This was related to the recent chrome sandboxing/docker permission updates. Should be fixed in v1.7.12
