### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by moshOntong-IT** [livekit/egress#510]
**Is your feature request related to a problem? Please describe.**

Currently, saving or exporting screen recording in cloud is supporting S3, Google Cloud, Digital Ocean and etc. However, this is costly to us especially on us as Student. Locally? maybe a best idea but we want to experience on saving the recording in cloud.

**Describe the solution you'd like**

I think it is a best idea to adapt or have support on Appwrite Storage in your list. Appwrite Storage does not complex at all they also provide API key and buckets Id, just similar to S3 or Azure.

**Comment by davidzhao** [comment]
Hi @moshOntong-IT, we do not plan on supporting AppWrite. S3 offers 5GB of free storage in their free tier, I suggest using that if cost is a concern.
