### ISSUE TITLE
[BUG] 0kb files / pipeline not playing

### ISSUE THREAD

**Issue by rafaelhutter** [livekit/egress#519]
Hi @frostbyte73 ,

thanks a lot for the great progress in this project. The quality of the recordings has improved drastically in the last versions.

We are experiencing problems with empty files with egress 1.7.12 in a Kubernetes Cluster. This happens in around 20 percent of the cases and we haven't found a pattern yet what could be the cause for this. 
The log for these cases has one thing in common which is, that the line: "pipeline playing" is missing:

> 2023-10-25T07:08:35.509Z	DEBUG	egress	stats/monitor.go:159	cpu check	{"nodeID": "NE_Uc6fSZKpbRRW", "clusterID": "", "total": 8, "available": 7.9989341300192685, "reserved": 0}
> 2023-10-25T07:08:36.016Z	DEBUG	egress	stats/monitor.go:159	cpu check	{"nodeID": "NE_Uc6fSZKpbRRW", "clusterID": "", "total": 8, "available": 7.9989341300192685, "reserved": 0}
> 2023-10-25T07:08:36.016Z	INFO	egress	service/service.go:123	request received	{"nodeID": "NE_Uc6fSZKpbRRW", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.018Z	INFO	egress	service/service.go:132	request validated	{"nodeID": "NE_Uc6fSZKpbRRW", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "requestType": "track_composite", "outputType": "file", "room": "test-mft-t-6hfo6e", "request": {"TrackComposite":{"room_name":"test-mft-t-6hfo6e","audio_track_id":"TR_AMZa8bNruuLcPM","video_track_id":"TR_VCaoAPWhFFHypo","Output":{"File":{"file_type":1,"filepath":"/out/clo5eyr8t000qf00r8f85qpag/20231025-070835_test-mft-t-6hfo6e_host_dx6xyp_01","Output":null}},"Options":{"Preset":2},"file_outputs":[{"file_type":1,"filepath":"/out/clo5eyr8t000qf00r8f85qpag/20231025-070835_test-mft-t-6hfo6e_host_dx6xyp_01","Output":null}]}}}
> 2023-10-25T07:08:36.048Z	DEBUG	egress	server/main.go:184	handler launched	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.049Z	INFO	egress	redis/redis.go:127	connecting to redis	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "simple": true, "addr": "moovit-redis-headless:6379"}
> 2023-10-25T07:08:36.065Z	DEBUG	egress	source/sdk.go:162	connecting to room	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.358Z	DEBUG	logger/logger.go:243	Using ICE servers	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "servers": [{"credential":"","credentialType":"password","urls":["stun:stun.l.google.com:19302","stun:stun1.l.google.com:19302"]}]}
> 2023-10-25T07:08:36.358Z	INFO	logger/logger.go:250	received offer for subscriber	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.365Z	INFO	logger/logger.go:250	ICE connected	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "iceCandidatePair": "(local) udp4 host 10.42.4.134:33897 <-> (remote) udp4 prflx 10.42.9.0:11880 related :0"}
> 2023-10-25T07:08:36.368Z	INFO	egress	source/sdk.go:291	subscribing to track	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "trackID": "TR_VCaoAPWhFFHypo"}
> 2023-10-25T07:08:36.369Z	INFO	egress	source/sdk.go:291	subscribing to track	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "trackID": "TR_AMZa8bNruuLcPM"}
> 2023-10-25T07:08:36.525Z	INFO	logger/logger.go:250	received offer for subscriber	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.573Z	INFO	logger/logger.go:250	track subscribed	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "participant": "clo5eyxu3000sf00r6jdx6xyp", "track": "TR_AMZa8bNruuLcPM", "kind": "audio"}
> 2023-10-25T07:08:36.629Z	INFO	logger/logger.go:250	track subscribed	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "participant": "clo5eyxu3000sf00r6jdx6xyp", "track": "TR_VCaoAPWhFFHypo", "kind": "video"}
> 2023-10-25T07:08:36.636Z	DEBUG	egress	gstreamer/bin.go:63	adding src TR_AMZa8bNruuLcPM to audio	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.636Z	DEBUG	egress	gstreamer/bin.go:63	adding src audio_test_src to audio	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.637Z	DEBUG	egress	gstreamer/bin.go:63	adding src audio to pipeline	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.640Z	DEBUG	egress	gstreamer/bin.go:63	adding src TR_VCaoAPWhFFHypo to video	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.640Z	DEBUG	egress	gstreamer/bin.go:63	adding src video_test_src to video	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.641Z	DEBUG	egress	gstreamer/bin.go:63	adding src video to pipeline	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.643Z	DEBUG	egress	gstreamer/bin.go:69	adding sink file to pipeline	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.647Z	DEBUG	egress	pipeline/controller.go:191	waiting for start signal	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.647Z	DEBUG	egress	gstreamer/state.go:75	pipeline state building -> starting	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.651Z	DEBUG	egress	gstreamer/state.go:75	pipeline state starting -> running	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.650Z	DEBUG	egress	[gst fixme] gst_video_decoder_drain_out: Sub-class should implement drain()	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst-libs/gst/video/gstvideodecoder.c:1199"}
> 2023-10-25T07:08:36.651Z	INFO	egress	pipeline/watch.go:233	TR_AMZa8bNruuLcPM playing	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:36.652Z	INFO	egress	pipeline/watch.go:233	TR_VCaoAPWhFFHypo playing	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:08:47.257Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 2880 samples = 0:00:00.060000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:08:51.139Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 5760 samples = 0:00:00.120000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:08:55.860Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 4800 samples = 0:00:00.100000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:08:57.032Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 2880 samples = 0:00:00.060000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:00.898Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 15360 samples = 0:00:00.320000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:07.732Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:08.159Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:08.573Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:08.990Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:09.414Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:09.837Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:10.254Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:10.701Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:11.094Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:11.520Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:11.937Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:12.352Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:12.772Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:13.195Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:13.617Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:14.038Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:14.451Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:14.874Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:15.298Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:15.716Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:16.132Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:16.559Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:16.972Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:17.398Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:17.816Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:18.233Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:18.660Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:19.078Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:19.493Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:19.920Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:20.340Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:20.752Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:21.179Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:21.599Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:22.014Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:22.439Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:22.858Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:23.275Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:23.558Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 11520 samples = 0:00:00.240000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:24.292Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:24.720Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:25.130Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:25.555Z	DEBUG	egress	[gst warning] gst_audio_resample_check_discont: encountered timestamp discontinuity of 18240 samples = 0:00:00.380000000	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "caller": "../gst/audioresample/gstaudioresample.c:732"}
> 2023-10-25T07:09:25.726Z	DEBUG	egress	pipeline/controller.go:358	Sending EOS	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:09:25.726Z	DEBUG	egress	gstreamer/state.go:75	pipeline state running -> stopping	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:09:25.730Z	DEBUG	egress	gstreamer/state.go:75	pipeline state stopping -> finished	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi"}
> 2023-10-25T07:09:25.753Z	INFO	egress	sdk/appwriter.go:225	writer finished	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "trackID": "TR_VCaoAPWhFFHypo", "kind": "video", "sampleDuration": "33.333333ms", "avgDrift": "0s", "maxDrift": "0s", "packetLoss": "0.00%"}
> 2023-10-25T07:09:25.753Z	INFO	egress	sdk/appwriter.go:225	writer finished	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "trackID": "TR_AMZa8bNruuLcPM", "kind": "audio", "sampleDuration": "135ms", "avgDrift": "0s", "maxDrift": "0s", "packetLoss": "0.00%"}
> 2023-10-25T07:09:25.754Z	INFO	egress	service/handler.go:226	egress updated	{"nodeID": "NE_Uc6fSZKpbRRW", "handlerID": "EGH_X9gzTPcdceS4", "clusterID": "", "egressID": "EG_WDyEcn64mkCi", "egressID": "EG_WDyEcn64mkCi", "requestType": "track_composite", "outputType": "file", "status": "EGRESS_ABORTED"}

Thanks a lot,

Rafael

**Comment by sklein-moov** [comment]
In the above setup I saw significant differences depending the browser I used.

Chromium: Video+Audio recordings: 4 out of 6 turned out to be 0B files, same for Video only. Audio always worked.
Firefox: Video+Audio recordings: only 2 out of 6 empty, Audio only and Video only also OK.

I tried different recording durations, 10, 20, 30s, 
In Chromium longer recordings, in my case 30s, seemed to work better, but the first seconds where cut off.
In Firefox the duration seemed not to matter.

Please tell me if I can help by providing more detailed information.

thanks for all the great work you guys invest in this project!

**Comment by frostbyte73** [comment]
What codecs are your tracks?

**Comment by rafaelhutter** [comment]
VP8 and H.264 for Video, depending on the browser, and ogg for audio.

**Comment by rafaelhutter** [comment]
I've found a way to reproduce a 0Kb every time:

```
egressClient.startTrackCompositeEgress(
          urlName,
          { ...output, fileType: EncodedFileType.MP4 },
          {
            audioTrackId,
            videoTrackId,
            encodingOptions: EncodingOptionsPreset.H264_1080P_30,
          }

```
Where output is an DirectFileOutput with a iOS Device and a muted/disabled video track

**Comment by heckm4n** [comment]
Hello everyone, could someone please assist with this issue? We've encountered this problem in one of our projects, and it has become a significant concern at the moment. Any assistance would be greatly appreciated. Thank you!

**Comment by pimswr** [comment]
We are also facing this problem at SWR in Germany, could you please assit ? Many thanks

**Comment by frostbyte73** [comment]
Fixed in https://github.com/livekit/egress/pull/524

**Comment by duckdiver** [comment]
Dear all,
we found the same issue with 0kB recordfiles in our egress project (v1.7.12) as @rafaelhutter mentioned above.
would be great to find a timely solution 👍

Thanks a lot to all the egress community!
