### ISSUE TITLE
[BUG] Egress can not always start in locall testing

### ISSUE THREAD

**Issue by braveyao** [livekit/egress#520]
**Describe the bug**
I found recently it is harder to do egress test locally on my Macbook. There are at least two issues that impact my tests, which lead to several questions.
 - StartEgress() won't be called after StartEgressAffinity() occasionally when the egress instance is idle. Since I only have one egress instance locally, so no matter what, the StartEgress should be invoked to the same instance.
 - Sometimes, it fails to join the room with error "could not connect after timeout". This issue also happens to Ingress. Repeating the request may work. Or restarting the egress/livekit instances may help too.

So the questions are:
1. Who is calling StartEgressAffinity()? I failed to find the place and can't check the logic why it won't call StartEgress() when there is enough CPU.
2. I noticed the Egress info won't be deleted from Redis after recording. What's reason?
3. How to debug the "could not connect after timeout"? Nothing suspicious from LiveKit server logs so far.

**Egress Version**
The latest Egress revision on Oct 23, commit 20b641f1fb4e9589c1f6d54846edb35ce7a17c17
The latest LiveKit revision on Oct 23, commit f4a361800000f269cc6b52614698e97f90970ad0

**Egress Request**
livekit-cli start-room-composite-egress

**Additional context**
This doesn't look like problem of Egress itself. I reversed to an old revision in Aug, which worked perfectly at that time. It still happens. So perhaps it's in other pkgs, like psrpc or livekit?

**Logs**
Can't find logs for issue 1. 
Let me know what logs I can help to collect for help.

**Comment by braveyao** [comment]
The "could not connect after timeout" issue becomes worse. I can barely do any egress tests today.
The LiveKit server only logs that ws got EOF.
```
2023-10-26T11:22:32.250-0700	INFO	livekit	service/rtcservice.go:299	new client WS connected	{"room": "my-first-room", "roomID": "RM_iAi9YraFdEUn", "participant": "EG_3XHBB5tgceir", "pID": "PA_U9b4NDjp3gFB", "remote": false, "connID": "CO_C8CE6h9bmjgt", "reconnect": false, "reconnectReason": "RR_UNKNOWN", "adaptiveStream": false}
2023-10-26T11:22:47.264-0700	INFO	livekit	service/rtcservice.go:375	exit ws read loop for closed connection	{"room": "my-first-room", "roomID": "RM_iAi9YraFdEUn", "participant": "EG_3XHBB5tgceir", "pID": "PA_U9b4NDjp3gFB", "remote": false, "connID": "CO_C8CE6h9bmjgt", "wsError": "websocket: close 1006 (abnormal closure): unexpected EOF"}
```
While successful case shows:
```
2023-10-26T13:33:17.762-0700	INFO	livekit.transport	rtc/transport.go:632	selected ICE candidate pair	{"room": "my-first-room", "roomID": "RM_GLLiTjCZjBY7", "participant": "EG_gVQAwsTyM3LL", "pID": "PA_jvz2obT5WVBE", "remote": false, "transport": "SUBSCRIBER", "pair": "(local) udp4 host 192.168.86.26:53624 <-> (remote) udp4 prflx 192.168.86.27:47095 related :0"}
2023-10-26T13:33:17.766-0700	INFO	livekit.transport	rtc/transport.go:1606	ice candidates ...
```

So which end, Egress or LiveKit, may be main cause? How to tackle this down?

**Comment by frostbyte73** [comment]
1. Psprc uses the affinity function (https://github.com/livekit/psrpc)
2. It will be deleted after 3 days, it's there so you can view any errors after failures
3. I'm not sure why you have connectivity issues while running locally - I'm unable to reproduce with a local setup. Check https://github.com/livekit/egress#running-locally to make sure it's set up correctly

**Comment by braveyao** [comment]
Thanks so much for the reply!

1. Now I see what the StartEgressAffinity() is. But why sometimes it won't select the only server?
2. I think I saw egress from months back.  :)
3. My setup used to work very well. The connectivity issue starts to emerge recently. I still can do some tests yesterday and almost can't do any today. That's super weird. I can't tell much from the failed and success cases from Livekit logs. Do you see anything suspicious? Any other ideas?

[connect-succeed.txt](https://github.com/livekit/egress/files/13184750/connect-succeed.txt)

[connect-timeout.txt](https://github.com/livekit/egress/files/13184748/connect-timeout.txt)

**Comment by frostbyte73** [comment]
It's definitely an issue with the egress instance connecting to your Livekit server:
```
"participant": "EG_3XHBB5tgceir", "pID": "PA_U9b4NDjp3gFB", "remote": false, "reason": "JOIN_FAILED"
```
I can't reproduce on my end, but I think it is probably related to your network

**Comment by braveyao** [comment]
Without doing much, except for rebooting my Mac several times(which didn't help when I filed this ticket.), it seems back to work as usual. So this is still kind of mystery. I'll see if I can tackle it down a bit when it happens again.
Thanks for your help! Close it for now.
