### ISSUE TITLE
[BUG] Corrupt audio track in some .ts files

### ISSUE THREAD

**Issue by SijmenHuizenga** [livekit/egress#531]
**Describe the bug**
_Some_ (not all) `.ts` files created by egress have a corrupt audio track.

**Egress Version**
We are using livekit cloud. This corrupt file was created on 2023-11-07 15:50:21.624Z

**Observed behavior**

I'm attaching two files:

* `testbed_20231107154427624.ts` This one has a good audio track definition. `ffplay` detects the audio as `Audio: aac (LC) ([15][0][0][0] / 0x000F), 44100 Hz, stereo, fltp, 7 kb/s`
* `testbed_20231107155021624.ts` This one is corrupt. The audio does not play. `ffplay` complains about a missing `estimate_timings_from_pts`, missing `codec parameters` and `unspecified sample rate`. It describes the audio stream as `Audio: aac ([15][0][0][0] / 0x000F), 0 channels, fltp`.

[corrupt-audio.zip](https://github.com/livekit/egress/files/13294450/corrupt-audio.zip)

![image](https://github.com/livekit/egress/assets/8008227/28f7cb06-98f8-43b8-9b4e-c348e97b8e27)

Both files were created during the same egress. These files were collected from the same egress as #530, but from what I can see these are two unrelated bugs.

**Additional context**
This recording was made in cloud project `p_2u70izoj75h` egresses `EG_hzVc5XuBuwp7`.

**Comment by SijmenHuizenga** [comment]
I've created a playlist with the two files above here:

https://videojs-repro.s3.eu-central-1.amazonaws.com/corrupt-audio-segment.m3u8

If you play this in video.js https://videojs-http-streaming.netlify.app you will experience the impact of this bug onto our application. At first the video seems to play fine, but as soon as it arrives at the corrupt file the video gets stuck.

**Comment by frostbyte73** [comment]
This one's going to take some digging. It looks like due to an ICE disconnection, the writers stopped recording track data at 10:21, but the track remained for another 5h

<img width="1060" alt="Screenshot 2023-11-09 at 1 03 44 PM" src="https://github.com/livekit/egress/assets/3291089/b4d73921-048f-4a25-a368-081564719906">

**Comment by frostbyte73** [comment]
Fixed in https://github.com/livekit/egress/pull/535

**Comment by SijmenHuizenga** [comment]
@frostbyte73 do you maybe know if this fix has been rolled out onto Livekit cloud?

I have run another test last night and got another corrupt .ts file at 2023-11-14 01:00:16 UTC. project p_2u70izoj75h egress EG_3Srt9qZDVGDD. File attached.

[531-another.zip](https://github.com/livekit/egress/files/13346472/531-another.zip)

**Comment by frostbyte73** [comment]
I just rolled it out to prod last night
