### ISSUE TITLE
ERROR: GST_PLUGIN_LOADING gstpluginloader.c:442:gst_plugin_loader_try_helper

### ISSUE THREAD

**Issue by thesanat** [livekit/egress#532]
I have a problem unable to send RTMP with egress:v1.7.9 and livekit-server:v1.5.0
Please help me
![Screenshot 2566-11-08 at 17 25 19](https://github.com/livekit/egress/assets/78894719/0fe20021-0d9a-4820-9da7-8dc0fede2191)

**Comment by frostbyte73** [comment]
`chrome: END_RECORDING` was sent due to no available tracks in the room, closing the egress
