### ISSUE TITLE
[BUG] invalid m3u8 created, EXT-X-TARGETDURATION is too small

### ISSUE THREAD

**Issue by SijmenHuizenga** [livekit/egress#534]
**Describe the bug**
We received a `.m3u8` file with the following content:
```
#EXTM3U
#EXT-X-VERSION:4
#EXT-X-PLAYLIST-TYPE:EVENT
#EXT-X-ALLOW-CACHE:NO
#EXT-X-TARGETDURATION:6
#EXT-X-MEDIA-SEQUENCE:0
[...]
#EXT-X-PROGRAM-DATE-TIME:2023-11-09T03:16:07.191Z
#EXTINF:6.000,
testbed_20231109031607191.ts
#EXT-X-PROGRAM-DATE-TIME:2023-11-09T03:16:13.191Z
#EXTINF:7.078,
testbed_20231109031613191.ts
#EXT-X-PROGRAM-DATE-TIME:2023-11-09T03:16:20.269Z
#EXTINF:6.006,
testbed_20231109031620269.ts
#EXT-X-PROGRAM-DATE-TIME:2023-11-09T03:16:26.275Z
#EXTINF:6.054,
testbed_20231109031626275.ts
#EXT-X-PROGRAM-DATE-TIME:2023-11-09T03:16:32.33Z
#EXTINF:8.138,
testbed_20231109031632330.ts
#EXT-X-PROGRAM-DATE-TIME:2023-11-09T03:16:40.467Z
#EXTINF:7.729,
testbed_20231109031640467.ts
```

The [rfc8216 section-4.3.3.1](https://datatracker.ietf.org/doc/html/rfc8216#section-4.3.3.1) describes `EXT-X-TARGETDURATION`:

> *The EXTINF duration of each Media Segment in the Playlist file, when rounded to the nearest integer, MUST be less than or equal to the target duration;

**Egress Version**
Livekit Cloud

**Additional context**
Our egress `segmentDuration` is set to `6`, this is probably where the `EXT-X-TARGETDURATION` comes from.

**Comment by frostbyte73** [comment]
Can you drop the egressID and/or request?

**Comment by SijmenHuizenga** [comment]
The example above is from project `p_2u70izoj75h` egresses `EG_hWhpJrf3K85V`.

**Comment by frostbyte73** [comment]
Closing as fixed
