### ISSUE TITLE
[BUG] Time jumps inside segment

### ISSUE THREAD

**Issue by SijmenHuizenga** [livekit/egress#537]
**Describe the bug**
Since #531 i continued testing with audio. Attaching 3 consecutive segments:

* `testbed_20231114010004779.ts` This one is a good segment. Nothing to note here
* `testbed_20231114010010779.ts` This segment makes video.js crash. When playing with ffplay, i see that there is a time-jump happening inside the segment. At the start time is around 02:00:10 (UTC+1), and then ~halfway into the segment the time jumps to around 02:01:18 (UTC+1). A full minute is skipped.
* `testbed_20231114010016779.ts`. According to the filename, this segment is 01:00:16 UTC, but the first frame shows 01:01:19 UTC. Time is off by a minute. Also note that this segment has the problem described in #531.

[timejump.zip](https://github.com/livekit/egress/files/13346435/timejump.zip)

**Egress Version**
Livekit cloud version

**Egress Request**
project p_2u70izoj75h egress EG_3Srt9qZDVGDD

**Comment by frostbyte73** [comment]
I don't see anything abnormal in the logs from that time, or even the surrounding ~hour. Will keep an eye on this, if you find any more examples please post them here

**Comment by frostbyte73** [comment]
Closing as fixed
