### ISSUE TITLE
[BUG]egress error : no response from servers

### ISSUE THREAD

**Issue by keaipeng123** [livekit/egress#575]
![image](https://github.com/livekit/egress/assets/90554992/9145f5e8-9465-490f-b2c3-c6ec7130a244)

livekit-server:v1.5.2
egress:v1.7.5

**Comment by serhiynovos** [comment]
@keaipeng123 does it happen in some time ? Look like it's the similar issue what I have

**Comment by davidzhao** [comment]
@keaipeng123, please upgrade Egress to 1.8.0.
