### ISSUE TITLE
[BUG] When I use egress to record my meeting,the egress has problems.

### ISSUE THREAD

**Issue by sunnysteam** [livekit/egress#596]
the problem display:
![image](https://github.com/livekit/egress/assets/19546500/241c7c99-ee47-4349-88a4-65d2ede6e97d)

my request:
{
    "room_name": "my-last12-room",
    "track_id": "TR_35",
    "file": {
        "filepath": "livekit-demo/track-test.mp4"
    }
}

The meeting is good running, but egress doen't work

**Comment by ashutoshmishraji** [comment]
As per logs, i think you are passing wrong track id . Please try with correct id
Thanks

**Comment by frostbyte73** [comment]
TR_35 is not a valid track ID
