### ISSUE TITLE
where to get token to auto egress?

### ISSUE THREAD

**Issue by AlexanderKozhevin** [livekit/egress#613]
**Describe the bug**
https://docs.livekit.io/egress-ingress/egress/autoegress/#Automatically-record-all-tracks-to-S3
I'm trying to call a method POST <your-host>/twirp/livekit.RoomService/CreateRoom
BUt getting an error 
```
{"code":"unauthenticated","msg":"permissions denied"}
```
I'm using token like for regular participant of videochat.
**Egress Version**
livekit/ingress:latest

{"code":"unauthenticated","msg":"permissions denied"}

**Comment by davidzhao** [comment]
You would need `roomCreate` and `roomRecord` permissions. See [auth docs](https://docs.livekit.io/realtime/concepts/authentication/) for details.
