### ISSUE TITLE
Error "Cannot read properties of undefined (reading 'size')" when Participant leaves

### ISSUE THREAD

**Issue by longlwu2000** [livekit/egress#664]
### Describe the bug

Error "Cannot read properties of undefined (reading 'size')" when Participant leaves

![image](https://github.com/livekit/client-sdk-js/assets/99626338/38db2988-ff07-4d4a-8ed9-3b8862d01407)

![image](https://github.com/livekit/client-sdk-js/assets/99626338/ed26b582-afcc-4341-b41e-7dd131d56a35)

### Reproduction

I encounter this error every time a user leaves the room.

### System Info

```shell
Chrome Version 124.0.6367.119 (64-bit)
```

### Severity

serious, but I can work around it

**Comment by lukasIO** [comment]
@longlwu2000 the 0.2.0 version of the egress SDK does not have that conde path in it.
Have a look at the `dist/` folder on [npm](https://www.npmjs.com/package/@livekit/egress-sdk/v/0.2.0?activeTab=code).
Make sure that your code is actually running 0.2.0.
