### ISSUE TITLE
S3 access key and secret

### ISSUE THREAD

**Issue by bmbferreira** [livekit/egress#73]
Hi! First let me thank you for the great work on this project 🙇 

I've been trying it out and recently deployed successfully both `livekit-server` and `livekit-egress` on a kubernetes cluster using the provided helm charts. All good, but I have some questions regarding the access key and secret to be able to upload to the S3 buckets:
1. First I was trying to use an AWS Role associated with a ServiceAccount to upload to the buckets from egress but then I quickly realised that the access key and secret were the only supported way. Would it be possible to use Role instead? I think it would be just a matter of using the Role defined on the environment and avoid setting the static credentials [here](https://github.com/livekit/egress/blob/0814f1937f30022c0e9ce6bbac399c7af5226c8e/pkg/pipeline/sink/upload.go#L36) right 🤔 ?
2. Why do we have the set the credentials for S3 both in the client side while calling egress API and also on the egress server side? 😕 

Thank you 🙇

**Comment by davidzhao** [comment]
Thank you for the kind words @bmbferreira ! 

1. It would be great to be able to support this. If you are open to creating a PR for it, we'd welcome it!
2. If you've set it on the server side, then you don't have to pass it in again on the client side. The server-side configuration serves as a set of defaults. What's passed in on each request will override those defaults. This is a more flexible approach so that if you wanted to use different keys/buckets, you can do so without having to deploy different egress instances.

**Comment by bmbferreira** [comment]
Hi @davidzhao! Thank you for your quick reply! I will surely try to find the time to open a PR to make that work with IAM roles 😃 

Still regarding point 2, I think I might have found an issue because I'm using livekit-cli to test the egress and if I don't pass the key and secret for the S3 on the `request.json` it crashes on the egress backend complaining that `S3 upload failed: EmptyStaticCreds: static credentials are empty`, so I think it is not usng the defaults that I set on the server 😕 

Here's how I'm testing it:
1. Create the room and the token:
```
> livekit-cli create-room --name test \
        --url wss://live.mydomain.dev/ \
        --api-key ... --api-secret ...

> livekit-cli create-token --join --api-key ... --api-secret ...     --room test --identity user
```

2.  Fo to https://example.livekit.io/ and put the token and url

3. Start egress:
```
> livekit-cli start-room-composite-egress \
        --url wss://live.mydomain.dev/ \
        --api-key ... --api-secret ... --request request.json

EgressID: EG_ji8QKA9RniPH Status: EGRESS_STARTING
```

4. Stop egress:
```
> livekit-cli stop-egress \
        --url wss://live.mydomain.dev/ \
        --api-key ... --api-secret ... --id EG_ji8QKA9RniPH

EgressID: EG_ji8QKA9RniPH Status: EGRESS_ENDING
```

If the request.json is like this, it works:
```json
{
  "room_name": "test",
  "layout": "test",
  "file": {
    "filepath": "test234oi2432.mp4",
     "s3": {
      "access_key": "asdasdasd",
      "secret": "asdasdasdasd",
      "region": "eu-west-1",
      "bucket": "mybucket"
    }
  }
}
```

But If I remove the s3 block on the request.json like this:
```json
{
  "room_name": "test",
  "layout": "test",
  "file": {
    "filepath": "test234oi2432.mp4"
  }
}
```
it fails with the following error:
```
[livekit-egress-57f46dbf87-5zqqg] {"level":"info","ts":1660359308.0928898,"logger":"egress","caller":"service/handler.go:129","msg":"egress updated","nodeID":"NE_5jmQHSSUy3uH","egressID":"EG_kn2fEXEVWbgk","status":"EGRESS_ACTIVE"} 
[livekit-egress-57f46dbf87-5zqqg] {"level":"info","ts":1660359320.3619847,"logger":"egress","caller":"service/handler.go:129","msg":"egress updated","nodeID":"NE_5jmQHSSUy3uH","egressID":"EG_kn2fEXEVWbgk","status":"EGRESS_ENDING"} 
[livekit-egress-57f46dbf87-5zqqg] {"level":"error","ts":1660359320.409415,"logger":"egress","caller":"pipeline/pipeline.go:309","msg":"could not upload file","nodeID":"NE_5jmQHSSUy3uH","egressID":"EG_kn2fEXEVWbgk","location":"S3","error":"EmptyStaticCreds: static credentials are empty","stacktrace":"github.com/livekit/egress/pkg/pipeline.(*Pipeline).storeFile\n\t/workspace/pkg/pipeline/pipeline.go:309\ngithub.com/livekit/egress/pkg/pipeline.(*Pipeline).Run\n\t/workspace/pkg/pipeline/pipeline.go:230\ngithub.com/livekit/egress/pkg/service.(*Handler).HandleRequest.func2\n\t/workspace/pkg/service/handler.go:59"} 
[livekit-egress-57f46dbf87-5zqqg] {"level":"error","ts":1660359320.4099617,"logger":"egress","caller":"service/handler.go:125","msg":"egress failed","nodeID":"NE_5jmQHSSUy3uH","egressID":"EG_kn2fEXEVWbgk","error":"S3 upload failed: EmptyStaticCreds: static credentials are empty","stacktrace":"github.com/livekit/egress/pkg/service.(*Handler).sendUpdate\n\t/workspace/pkg/service/handler.go:125\ngithub.com/livekit/egress/pkg/service.(*Handler).HandleRequest\n\t/workspace/pkg/service/handler.go:70\nmain.runHandler\n\t/workspace/cmd/server/main.go:147\ngithub.com/urfave/cli/v2.(*Command).Run\n\t/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/command.go:163\ngithub.com/urfave/cli/v2.(*App).RunContext\n\t/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:313\ngithub.com/urfave/cli/v2.(*App).Run\n\t/root/go/pkg/mod/github.com/urfave/cli/v2@v2.3.0/app.go:224\nmain.main\n\t/workspace/cmd/server/main.go:65\nruntime.main\n\t/usr/lib/go-1.16/src/runtime/proc.go:225"} 
```

Also, I can confirm that on the egress it is well configured. If I do `kubectl exec -it livekit-egress-57f46dbf87-5zqqg -n livekit  -- env` in one of the pods, this is what I get on the config:
```
...
EGRESS_CONFIG_BODY=api_key: something
api_secret: something_secret
health_port: 8080
log_level: info
prometheus_port: 9090
redis:
  address: somecache.somewhere.ng.999.euw1.cache.amazonaws.com:6379
s3:
  access_key: mykey
  access_secret: mysecret
  bucket: mybucket
  region: eu-west-1
ws_url: wss://live.mydomain.dev
...
```

What am I missing? 

Thanks again for your help!

**Comment by biglittlebigben** [comment]
Hi! I believe the S3 conf in the example above has `access_secret` for the secret field, while `secret` is expected.

Just to make sure we do not have a mistake in our documentation: Is there any place in the website, examples, or source code where the field is listed as `access_secret`? (We could not find any, but may have missed something).

Thanks!

**Comment by bmbferreira** [comment]
🤦‍♂️ nice catch @biglittlebigben. I think that was exactly the issue! I was setting `access_secret` on the helm values instead of just `secret`, like it is on the example [here](https://github.com/livekit/livekit-helm/blob/master/examples/egress.yaml#L14). Thank you! 🙇

**Comment by bmbferreira** [comment]
maybe I can just leave this issue open to implement support for IAM roles instead? 🤔

**Comment by biglittlebigben** [comment]
Please create a new ticket for a feature request for better clarity. Thanks.

**Comment by iserranovimi** [comment]
The are plans to include passing dynamic token instead passing empty string?https://github.com/livekit/egress/blob/bdc2425142d6df145948831d0c80060be81b6ea2/pkg/pipeline/sink/upload.go#L41

We want to create S3 credentials on the fly from AWS with auto generated access token.
