### ISSUE TITLE
Idea: add fit/fill options for TrackCompositeEgressRequest_Advanced

### ISSUE THREAD

**Issue by mwk24** [livekit/egress#74]
Not sure what the perfect solution is..., but right now if I have a vertical input video (for example, from a phone), I would need to set the aspect ratio using TrackCompositeEgressRequest_Advanced. Maybe this is fine, just wondering if fit/fill might be useful.

**Comment by davidzhao** [comment]
it would make sense for us. to have a few presets. and yeah! having a fit/fill would be a good option to have too.
