### ISSUE TITLE
Support for IAM roles to access S3

### ISSUE THREAD

**Issue by bmbferreira** [livekit/egress#75]
Hi! Seems that currently it is required to always set an access key and secret to access the S3 bucket to save the files. Ideally, it should be possible to use AWS IAM Roles associated with a ServiceAccount instead, since it is more secure. 
I think it would be just a matter of using the Role defined on the environment and avoid setting the static credentials [here](https://github.com/livekit/egress/blob/0814f1937f30022c0e9ce6bbac399c7af5226c8e/pkg/pipeline/sink/upload.go#L36).

I can go for it when I have some free time, just creating the issue here in case someone wants to go first 😄 Thank you!

**Comment by frostbyte73** [comment]
Added in https://github.com/livekit/egress/pull/177

**Comment by sinkr** [comment]
Hi, @bmbferreira thank you for this.  Would you be so kind as to explain how employ this method versus static credentials?  Apologies if this is a daft question, however, in the past providers have provided account credentials we can add to policy and this seems to be the missing piece to me.
