### ISSUE TITLE
Any way to self-host egress and use livekit community cloud server?

### ISSUE THREAD

**Issue by hari01584** [livekit/egress#773]
We want to use live kit community server having LIVEKIT_URL as something like wss://*.livekit.cloud with our self-hosted egress..

Current egress limitation (2 concurrent connection) is too low, but we cannot afford scale plan or self-host (due to geo-replication and multi-region deployment needs)..

Is there any way to standalone host egress (this repo) and work it without this limitation of 2 concurrent connection? Maybe directly instructing server to start recording a room

**Comment by davidzhao** [comment]
@hari01584 there are no concurrent Egress limitations when you are on the Ship plan. If you are on that plan, feel free to request limit increases in Settings.

I can see that our docs aren't very clear on this topic, we'll get that updated.
