### ISSUE TITLE
[FEATURE] Add Support for --ignore-certificate-errors in LiveKit Egress for Self-Signed Certificates

### ISSUE THREAD

**Issue by rlatmd0829** [livekit/egress#804]
Could you please add support for the --ignore-certificate-errors flag in LiveKit Egress to allow Chrome to load pages with self-signed certificates?

**Comment by shoyu666** [comment]
add ignore-certificate-errors=true and  mute-audio=false
try https://hub.docker.com/repository/docker/shoyu666/egress/general
