### ISSUE TITLE
[BUG] Triple placement of files in S3

### ISSUE THREAD

**Issue by alankashkash** [livekit/egress#805]
**Describe the bug**
Triple placement of files in S3 (check timestamps). All are duplicates of each other.
![image](https://github.com/user-attachments/assets/90382492-7fd0-4582-9d35-6577dfe86aed)

**Egress Version**
Python SDKs:
livekit                                            0.18.0
livekit-agents                                     0.11.1
livekit-api                                        0.7.1
livekit-protocol                                   0.6.0

**Egress Request**
async def start_room_egress(agent_type: str, room_name, participant_sid):
    req = api.RoomCompositeEgressRequest(
        room_name=room_name,
        layout="speaker",
        preset=api.EncodingOptionsPreset.H264_720P_30,
        audio_only=False,
    )
    req.file_outputs.extend([api.EncodedFileOutput(
        filepath=f"{participant_sid}.mp4",
        s3=api.S3Upload(
            access_key=os.getenv('S3_LIVEKIT_BUCKET_ACCESS_KEY'),
            secret=os.getenv('S3_LIVEKIT_BUCKET_SECRET'),
            bucket="",
            region="",
        )
    )])
    if agent_type == "realtime":
        lkapi = api.LiveKitAPI(
            url=os.getenv('RTA_LIVEKIT_URL'), 
            api_key=os.getenv('RTA_LIVEKIT_API_KEY'), 
            api_secret=os.getenv('RTA_LIVEKIT_API_SECRET')
        )
    elif agent_type == "four_models":
        lkapi = api.LiveKitAPI(
            url=os.getenv('FMA_LIVEKIT_URL'), 
            api_key=os.getenv('FMA_LIVEKIT_API_KEY'), 
            api_secret=os.getenv('FMA_LIVEKIT_API_SECRET')
        )
    res = await lkapi.egress.start_room_composite_egress(req)

**Additional context**

**Logs**
Post any relevant logs from the egress service here.

**Comment by davidzhao** [comment]
these are different files. nothing is duplicated here.

**Comment by alankashkash** [comment]
@davidzhao ids are different but content is the same. Triple checked that. Here's another example of a different interview:
![image](https://github.com/user-attachments/assets/d16c6c24-fbcc-4a32-9553-959dc61c8fcb)

**Comment by davidzhao** [comment]
the file sizes and timestamps look different to me.. what are you seeing that I'm not?

**Comment by davidzhao** [comment]
We do not store the files on our side. They are uploaded directly to your bucket. these are two different participantIDs and to me that means the Egress API is working correctly.
